version: "3.8"

services:
  app:
    image: suayb/reactive-app:main
    container_name: app
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
    healthcheck:
      test: curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: app-base-config

networks:
  app:
    driver: "bridge"
