apiVersion: v1
kind: Secret
metadata:
    name: {{ template "graalvm-native-app.fullname" . }}
    namespace: {{ include "graalvm-native-app.namespace" . | quote }}
    labels: {{- include "graalvm-native-app.labels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "graalvm-native-app.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
   {{- end }}
type: Opaque
data:
    secret-data: {{ .Values.spring.secretData | b64enc | quote }}

